# Source: https://github.com/marketplace/actions/label-sync

name: Sync labels
on:
  workflow_dispatch:
  schedule:
    - cron:  '00 5 * * *'

jobs:
  labels:
    name: Pull & Import Labels
    runs-on: ubuntu-latest

    steps:
      - uses: EndBug/label-sync@v2
        with:
          config-file: https://raw.githubusercontent.com/GovA11y/.github/main/.github/configs/labels.yml
          # If you're using a private source repo or a URL that needs an 'Authorization' header, you'll need to add a custom token for the action to read it
          request-token: ${{ secrets.BOT_TOKEN }}

          # If you want to delete any additional label, set this to true
          delete-other-labels: true

          # If you want the action just to show you the preview of the changes, without actually editing the labels, set this to true
          dry-run: false

          # You can change the token used to change the labels, this is the default one
          token: ${{ secrets.BOT_TOKEN }}