# Source: https://github.com/marketplace/actions/label-sync

name: Sync labels
on:
  workflow_dispatch:
  schedule:
    - cron:  '00 5 * * *'

jobs:
  label-admin-repo:
    name: Sync Labels to .github
    runs-on: ubuntu-latest

    steps:
      - uses: EndBug/label-sync@v2
        with:
          config-file: https://raw.githubusercontent.com/GovA11y/.github/main/.github/configs/labels.yml
          # If you're using a private source repo or a URL that needs an 'Authorization' header, you'll need to add a custom token for the action to read it
          request-token: ${{ secrets.BOT_TOKEN }}

          # If you want to delete any additional label, set this to true
          delete-other-labels: true

          # If you want the action just to show you the preview of the changes, without actually editing the labels, set this to true
          dry-run: false

          # You can change the token used to change the labels, this is the default one
          token: ${{ secrets.BOT_TOKEN }}

# Source: https://github.com/marketplace/actions/label-syncer
  label-org-repos:
    name: Label Org Repos
    runs-on: ubuntu-latest
    needs: label-admin-repo
    steps:
      - uses: actions/checkout@v2
      - uses: micnncim/action-label-syncer@v1
        with:
          manifest: .github/configs/labels.yml
          repository: |
              GovA11y/reports
              GovA11y/module-complexity
              GovA11y/docs
              GovA11y/processor
              GovA11y/getting-started
              GovA11y/module-template
              GovA11y/k8s
              GovA11y/module-axe
              GovA11y/carbon-calculator
          token: ${{ secrets.BOT_TOKEN }}